services:
  web:
    build: .
    network_mode: host
    environment:
      APP_NAME: "Light Monitor"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:bGIbq7rOviZJpPsJgkwn3iCktltJ7JLkNH0N5dpgztQ=
      APP_URL: http://localhost:80
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: esp8266_light
      DB_USERNAME: root
      DB_PASSWORD: lightpass
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
      ESP_IP: 192.168.88.248        # IP ESP8266 sensor cahaya
      ESP_RELAY_IP: 192.168.88.247  # IP ESP8266 relay control
      ESP_TEMP_IP: 192.168.88.169   # IP ESP32 sensor suhu SHT40
      ESP_TIMEOUT: 5
      TZ: Asia/Jakarta
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: lightpass
      MARIADB_DATABASE: esp8266_light
      TZ: Asia/Jakarta
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  db_data:
