CREATE DATABASE IF NOT EXISTS esp8266_light
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE esp8266_light;

CREATE TABLE IF NOT EXISTS light_readings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    lux FLOAT NOT NULL,
    recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_recorded_at (recorded_at)
) ENGINE=InnoDB;
